/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZespolRouteImport } from './routes/zespol'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as UmowWizyteRouteImport } from './routes/umow-wizyte'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CennikRouteImport } from './routes/cennik'
import { Route as IndexRouteImport } from './routes/index'

const ZespolRoute = ZespolRouteImport.update({
  id: '/zespol',
  path: '/zespol',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const UmowWizyteRoute = UmowWizyteRouteImport.update({
  id: '/umow-wizyte',
  path: '/umow-wizyte',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CennikRoute = CennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/dashboard': typeof DashboardRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/umow-wizyte': typeof UmowWizyteRoute
  '/uslugi': typeof UslugiRoute
  '/zespol': typeof ZespolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/dashboard': typeof DashboardRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/umow-wizyte': typeof UmowWizyteRoute
  '/uslugi': typeof UslugiRoute
  '/zespol': typeof ZespolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/dashboard': typeof DashboardRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/umow-wizyte': typeof UmowWizyteRoute
  '/uslugi': typeof UslugiRoute
  '/zespol': typeof ZespolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cennik'
    | '/dashboard'
    | '/kontakt'
    | '/sitemap.xml'
    | '/umow-wizyte'
    | '/uslugi'
    | '/zespol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cennik'
    | '/dashboard'
    | '/kontakt'
    | '/sitemap.xml'
    | '/umow-wizyte'
    | '/uslugi'
    | '/zespol'
  id:
    | '__root__'
    | '/'
    | '/cennik'
    | '/dashboard'
    | '/kontakt'
    | '/sitemap.xml'
    | '/umow-wizyte'
    | '/uslugi'
    | '/zespol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CennikRoute: typeof CennikRoute
  DashboardRoute: typeof DashboardRoute
  KontaktRoute: typeof KontaktRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UmowWizyteRoute: typeof UmowWizyteRoute
  UslugiRoute: typeof UslugiRoute
  ZespolRoute: typeof ZespolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zespol': {
      id: '/zespol'
      path: '/zespol'
      fullPath: '/zespol'
      preLoaderRoute: typeof ZespolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umow-wizyte': {
      id: '/umow-wizyte'
      path: '/umow-wizyte'
      fullPath: '/umow-wizyte'
      preLoaderRoute: typeof UmowWizyteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cennik': {
      id: '/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof CennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CennikRoute: CennikRoute,
  DashboardRoute: DashboardRoute,
  KontaktRoute: KontaktRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UmowWizyteRoute: UmowWizyteRoute,
  UslugiRoute: UslugiRoute,
  ZespolRoute: ZespolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
